{
    'name': 'Task',
    'summary': 'Product And Sale Customization',
    'description': ''' Product And Sale Customization''',
    'version': '16.0.1.0.0',
    'author': 'shafi pk',
    'category': 'task ',
    'depends': ['base', 'sale', 'purchase', 'hr', 'project', 'contacts'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'data': [
        'security/user_group.xml',
        'security/ir.model.access.csv',
        'security/group_selected_user.xml',
        'views/purchase.xml',
        'views/hr_employee.xml',
        'views/res_partner.xml',
        'report/purchase_report.xml',
        'views/product_master.xml',
        'views/sale_order.xml',
        'views/clothes.xml',
        'views/email_templates.xml',
        'views/product_sequence.xml',
        'report/invoice_report.xml',
        'views/vehicle_accessories.xml',
        'views/school_accessories.xml',
        'views/hr_employee.xml',
        'views/sale_order_line.xml',
        'views/product_brand.xml',
        'report/sale_report.xml',
        'views/vendor_sequence.xml',
        'views/customer_sequence.xml',
        'views/food_item.xml',
        'views/project_project.xml',
        'views/material_view.xml',
        'views/account_move.xml',
        'views/update_price_wizard.xml',
        'views/employee.xml',
        # 'report/employee_report.xml',
        'views/hr_jobs.xml',
        'views/employee_review_wizard.xml',
        'views/menu.xml',
    ],
        'images':['static/description/icon.png'],
}
