from . import purchase
from . import clothmaster
from . import res_partner
from . import product_master
from . import sale_order
from . import sale_order_line
from . import account_move
from . import product_brand
from . import vehicle_accessories
from . import hr_employee
from . import school_accessories
from . import food_item
from . import project_project
from . import material
from . import employee_master